name: Run hardhat tests

on:
    pull_request:
    workflow_dispatch:

jobs:
    run-tests:
        name: Run hardhat tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Use Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Build
              run: |
                  yarn install
                  yarn compile

            - name: Run hardhat tests
              run: yarn test
